//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantation_kokoinum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture_table
    {
        public int Код { get; set; }
        public string Название { get; set; }
        public string Семейство { get; set; }
    }
}
