//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantation_kokoinum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts_table
    {
        public int Код { get; set; }
        public string Название_района { get; set; }
        public string Название_области { get; set; }
        public string Фамилия_главы_администрации { get; set; }
    }
}
