//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantation_kokoinum
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productivity_table
    {
        public int Код { get; set; }
        public Nullable<int> Код_культуры { get; set; }
        public Nullable<int> Код_района { get; set; }
        public Nullable<decimal> Урожайность_в_ц_га { get; set; }
    }
}
